name: Deploy CryptonicAPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Run Unit Tests
      run:
        dotnet test CryptonicAPI.Tests/CryptonicAPI.Tests.csproj

    - name: Build and Publish
      run: dotnet publish CryptonicAPI/CryptonicAPI.csproj -c Release -r linux-x64 --self-contained true -o out

    - name: Generate Deployment Package
      run:
        cd out
        zip -r ../deploy.zip .

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 'CryptonicAPI'
        environment_name: 'CryptonicAPI-env'
        version_label: "v-${{ github.run_id }}"
        region: eu-north-1
        deployment_package: deploy.zip
