name: Deploy CryptonicAPI to AWS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Hitta och Bygg Appen (Auto-Detect)
      run: |
        PROJECT_PATH=$(find . -name "*.csproj" | head -n 1)
        
        if [ -z "$PROJECT_PATH" ]; then
          echo "FEL: Hittade ingen .csproj fil! Kolla att du pushat koden."
          exit 1
        fi

        echo "Hittade projektfilen h√§r: $PROJECT_PATH"
        
        dotnet publish "$PROJECT_PATH" -c Release -r linux-x64 --self-contained true -o out

    - name: Skapa Zip-fil
      run: |
        cd out
        zip -r ${{ github.workspace }}/deploy.zip .

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 'CryptonicAPI'
        environment_name: 'CryptonicAPI-env'
        version_label: "v-${{ github.run_id }}"
        region: eu-north-1
        deployment_package: deploy.zip
